version: '3'

services:
    frontend:
        build: front-end/build/
        container_name: frontend
        depends_on:
          - 'backend'
        ports:
          - 3001:3001
    backend:
        build: backend/
        container_name: backend
        depends_on:
            - 'database'
        ports:
            - 3000:3000

    database:
        image: postgres
        container_name: database
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/database.sql
        environment:
            POSTGRES_PASSWORD: "password"
            POSTGRES_USER: "postgres"
            POSTGRES_DB: "pif"
